### ISSUE TITLE
I cant Build the project 

### ISSUE THREAD

**Issue by Valter-hatten** [Misat11/HybridMC#1]
the title says it all

**Comment by Misat11** [comment]
Hello @Valter-hatten . Can you paste the log from maven?

**Comment by Valter-hatten** [comment]
here


[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for misat11.hybrid:HybridMC-plugin:jar:0.0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-shade-plugin is missing. @ misat11.hybrid:HybridMC-plugin:[unknown-version], /home/WestEU/HybridMC/plugin/pom.xml, line 70, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] HybridMC-parent
[INFO] HybridMC-api
[INFO] HybridMC-protocol-common
[INFO] HybridMC-protocol-java
[INFO] HybridMC-protocol-bedrock
[INFO] HybridMC-common
[INFO] HybridMC-flattening
[INFO] HybridMC-legacy
[INFO] HybridMC-bukkit
[INFO] HybridMC-plugin
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building HybridMC-parent 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building HybridMC-api 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ HybridMC-api ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/WestEU/HybridMC/api/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ HybridMC-api ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ HybridMC-api ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/WestEU/HybridMC/api/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ HybridMC-api ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ HybridMC-api ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ HybridMC-api ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /home/WestEU/HybridMC/api/target/HybridMC-api-0.0.1-SNAPSHOT.jar
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building HybridMC-protocol-common 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ HybridMC-protocol-common ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/WestEU/HybridMC/protocol-common/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ HybridMC-protocol-common ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ HybridMC-protocol-common ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/WestEU/HybridMC/protocol-common/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ HybridMC-protocol-common ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ HybridMC-protocol-common ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ HybridMC-protocol-common ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /home/WestEU/HybridMC/protocol-common/target/HybridMC-protocol-common-0.0.1-SNAPSHOT.jar
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building HybridMC-protocol-java 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.nukkitx.com/snapshot/com/github/steveice10/opennbt/1.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.github.steveice10:opennbt:1.1-SNAPSHOT/maven-metadata.xml from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/com/github/steveice10/opennbt/1.1-SNAPSHOT/maven-metadata.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
[WARNING] Failure to transfer com.github.steveice10:opennbt:1.1-SNAPSHOT/maven-metadata.xml from http://repo.nukkitx.com/snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of nukkitx-repo has elapsed or updates are forced. Original error: Could not transfer metadata com.github.steveice10:opennbt:1.1-SNAPSHOT/maven-metadata.xml from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/com/github/steveice10/opennbt/1.1-SNAPSHOT/maven-metadata.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
Downloading: http://repo.nukkitx.com/snapshot/com/github/steveice10/packetlib/1.3-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.github.steveice10:packetlib:1.3-SNAPSHOT/maven-metadata.xml from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/com/github/steveice10/packetlib/1.3-SNAPSHOT/maven-metadata.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
[WARNING] Failure to transfer com.github.steveice10:packetlib:1.3-SNAPSHOT/maven-metadata.xml from http://repo.nukkitx.com/snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of nukkitx-repo has elapsed or updates are forced. Original error: Could not transfer metadata com.github.steveice10:packetlib:1.3-SNAPSHOT/maven-metadata.xml from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/com/github/steveice10/packetlib/1.3-SNAPSHOT/maven-metadata.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
Downloading: http://repo.nukkitx.com/snapshot/com/github/steveice10/mcauthlib/1.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.github.steveice10:mcauthlib:1.1-SNAPSHOT/maven-metadata.xml from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/com/github/steveice10/mcauthlib/1.1-SNAPSHOT/maven-metadata.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
[WARNING] Failure to transfer com.github.steveice10:mcauthlib:1.1-SNAPSHOT/maven-metadata.xml from http://repo.nukkitx.com/snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of nukkitx-repo has elapsed or updates are forced. Original error: Could not transfer metadata com.github.steveice10:mcauthlib:1.1-SNAPSHOT/maven-metadata.xml from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/com/github/steveice10/mcauthlib/1.1-SNAPSHOT/maven-metadata.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ HybridMC-protocol-java ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/WestEU/HybridMC/protocol-java/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ HybridMC-protocol-java ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 323 source files to /home/WestEU/HybridMC/protocol-java/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ HybridMC-protocol-java ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/WestEU/HybridMC/protocol-java/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ HybridMC-protocol-java ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ HybridMC-protocol-java ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ HybridMC-protocol-java ---
[INFO] Building jar: /home/WestEU/HybridMC/protocol-java/target/HybridMC-protocol-java-0.0.1-SNAPSHOT.jar
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building HybridMC-protocol-bedrock 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.nukkitx.com/snapshot/com/nukkitx/network/query/1.2.3-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.nukkitx.network:query:1.2.3-SNAPSHOT/maven-metadata.xml from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/com/nukkitx/network/query/1.2.3-SNAPSHOT/maven-metadata.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
[WARNING] Failure to transfer com.nukkitx.network:query:1.2.3-SNAPSHOT/maven-metadata.xml from http://repo.nukkitx.com/snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of nukkitx-repo has elapsed or updates are forced. Original error: Could not transfer metadata com.nukkitx.network:query:1.2.3-SNAPSHOT/maven-metadata.xml from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/com/nukkitx/network/query/1.2.3-SNAPSHOT/maven-metadata.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
Downloading: http://repo.nukkitx.com/snapshot/com/nukkitx/network/query/1.2.3-SNAPSHOT/query-1.2.3-SNAPSHOT.pom
Downloading: http://repo.nukkitx.com/snapshot/com/nukkitx/network/raknet/1.2.3-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.nukkitx.network:raknet:1.2.3-SNAPSHOT/maven-metadata.xml from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/com/nukkitx/network/raknet/1.2.3-SNAPSHOT/maven-metadata.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
[WARNING] Failure to transfer com.nukkitx.network:raknet:1.2.3-SNAPSHOT/maven-metadata.xml from http://repo.nukkitx.com/snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of nukkitx-repo has elapsed or updates are forced. Original error: Could not transfer metadata com.nukkitx.network:raknet:1.2.3-SNAPSHOT/maven-metadata.xml from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/com/nukkitx/network/raknet/1.2.3-SNAPSHOT/maven-metadata.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
Downloading: http://repo.nukkitx.com/snapshot/com/nukkitx/network/raknet/1.2.3-SNAPSHOT/raknet-1.2.3-SNAPSHOT.pom
Downloading: http://repo.nukkitx.com/snapshot/com/nukkitx/nbt/1.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.nukkitx:nbt:1.0.0-SNAPSHOT/maven-metadata.xml from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/com/nukkitx/nbt/1.0.0-SNAPSHOT/maven-metadata.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
[WARNING] Failure to transfer com.nukkitx:nbt:1.0.0-SNAPSHOT/maven-metadata.xml from http://repo.nukkitx.com/snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of nukkitx-repo has elapsed or updates are forced. Original error: Could not transfer metadata com.nukkitx:nbt:1.0.0-SNAPSHOT/maven-metadata.xml from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/com/nukkitx/nbt/1.0.0-SNAPSHOT/maven-metadata.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
Downloading: http://repo.nukkitx.com/snapshot/com/nukkitx/nbt/1.0.0-SNAPSHOT/nbt-1.0.0-SNAPSHOT.pom
Downloading: http://repo.nukkitx.com/snapshot/cn/nukkit/nukkit-natives/1.0.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata cn.nukkit:nukkit-natives:1.0.1-SNAPSHOT/maven-metadata.xml from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/cn/nukkit/nukkit-natives/1.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
[WARNING] Failure to transfer cn.nukkit:nukkit-natives:1.0.1-SNAPSHOT/maven-metadata.xml from http://repo.nukkitx.com/snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of nukkitx-repo has elapsed or updates are forced. Original error: Could not transfer metadata cn.nukkit:nukkit-natives:1.0.1-SNAPSHOT/maven-metadata.xml from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/cn/nukkit/nukkit-natives/1.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
Downloading: http://repo.nukkitx.com/snapshot/cn/nukkit/nukkit-natives/1.0.1-SNAPSHOT/nukkit-natives-1.0.1-SNAPSHOT.pom
Downloading: http://repo.nukkitx.com/snapshot/org/iq80/leveldb/leveldb/0.10-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.iq80.leveldb:leveldb:0.10-SNAPSHOT/maven-metadata.xml from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/org/iq80/leveldb/leveldb/0.10-SNAPSHOT/maven-metadata.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
[WARNING] Failure to transfer org.iq80.leveldb:leveldb:0.10-SNAPSHOT/maven-metadata.xml from http://repo.nukkitx.com/snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of nukkitx-repo has elapsed or updates are forced. Original error: Could not transfer metadata org.iq80.leveldb:leveldb:0.10-SNAPSHOT/maven-metadata.xml from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/org/iq80/leveldb/leveldb/0.10-SNAPSHOT/maven-metadata.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
Downloading: http://repo.nukkitx.com/snapshot/org/iq80/leveldb/leveldb/0.10-SNAPSHOT/leveldb-0.10-SNAPSHOT.pom
Downloading: http://repo.nukkitx.com/snapshot/net/minidev/json-smart/maven-metadata.xml
[WARNING] Could not transfer metadata net.minidev:json-smart/maven-metadata.xml from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/net/minidev/json-smart/maven-metadata.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] HybridMC-parent .................................... SUCCESS [  0.007 s]
[INFO] HybridMC-api ....................................... SUCCESS [  1.763 s]
[INFO] HybridMC-protocol-common ........................... SUCCESS [  0.047 s]
[INFO] HybridMC-protocol-java ............................. SUCCESS [ 12.452 s]
[INFO] HybridMC-protocol-bedrock .......................... FAILURE [  1.822 s]
[INFO] HybridMC-common .................................... SKIPPED
[INFO] HybridMC-flattening ................................ SKIPPED
[INFO] HybridMC-legacy .................................... SKIPPED
[INFO] HybridMC-bukkit .................................... SKIPPED
[INFO] HybridMC-plugin .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.373 s
[INFO] Finished at: 2018-11-17T11:02:52+00:00
[INFO] Final Memory: 20M/77M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project HybridMC-protocol-bedrock: Could not resolve dependencies for project misat11.hybrid:HybridMC-protocol-bedrock:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at com.nukkitx.network:query:jar:1.2.3-SNAPSHOT: Failed to read artifact descriptor for com.nukkitx.network:query:jar:1.2.3-SNAPSHOT: Could not transfer artifact com.nukkitx.network:query:pom:1.2.3-SNAPSHOT from/to nukkitx-repo (http://repo.nukkitx.com/snapshot/): Failed to transfer file: http://repo.nukkitx.com/snapshot/com/nukkitx/network/query/1.2.3-SNAPSHOT/query-1.2.3-SNAPSHOT.pom. Return code is: 500 , ReasonPhrase:Internal Server Error. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :HybridMC-protocol-bedrock

**Comment by Misat11** [comment]
The problem is that NukkitX repository is down. So we must wait for now because in this repository are some important libraries used in this project

**Comment by Valter-hatten** [comment]
ok do you have an already build version

**Comment by Misat11** [comment]
Yes, I have but I'm not on computer now, I'll send you a jar file when I have time

**Comment by Valter-hatten** [comment]
ok

**Comment by Misat11** [comment]
https://drive.google.com/file/d/1t_bBWDVFmNqnnM9mxDDZZ39g-UY-70Tt/view?usp=sharing
So there is a link to jar file. It's for spigot 1.13.2 and it support 1.7 Bedrock clients. Now it has a lot of bugs, so If you want to help me, you can open issues or make pull request.

**Comment by Valter-hatten** [comment]
thx dude
